amberframework/granite

- Projectfile
- README.md
- shard.yml
- src/sqlite_adapter.cr
- shards as dependency manager
- `TimeFormat` -> `Time::Format`
> Crystal 0.8.0 support

- src/kemalyst-model.cr
updated_at did not get updated
> Update updated_at field and not a local var.

- src/adapter/base.cr
- src/adapter/mysql.cr
- src/adapter/pg.cr
- src/adapter/sqlite.cr
- src/kemalyst-model.cr
Clean up the code.  Moved execution into the adapters.
> Optimizations

- spec/adapter/mysql_migrate_spec.cr
- spec/adapter/mysql_spec.cr
- spec/adapter/pg_migrate_spec.cr
- spec/adapter/pg_spec.cr
- spec/adapter/sqlite_migrate_spec.cr
- spec/adapter/sqlite_spec.cr
- spec/kemalyst-model_spec.cr
- src/adapter/base.cr
- src/adapter/mysql.cr
- src/adapter/pg.cr
- src/adapter/sqlite.cr
- src/kemalyst-model.cr
added specs as well, but I only tested the mysql spec. (PG won't install on ubuntu bash for windows, and I'm not sure about sqlite but I don't have it installed)
also I ran `crystal tool format`.
> decouple find from id

- src/adapter/base.cr
https://github.com/drujensen/kemalyst-model/issues/24
> Use DATABASE_URL by default if exists.

- spec/adapter/mysql_spec.cr
- spec/adapter/pg_spec.cr
- spec/adapter/sqlite_spec.cr
- src/adapter/base.cr
- src/adapter/mysql.cr
- src/adapter/pg.cr
- src/adapter/sqlite.cr
- src/kemalyst-model.cr
Implements feature as discussed in issue https://github.com/drujensen/kemalyst-model/issues/27
> Added support for custom primary key column name and type

- shard.yml
- spec/adapter/mysql_spec.cr
- src/adapter/base.cr
- src/kemalyst-model.cr
I replaced the modules :: with _ for the table name.  This is similar to
what rails does.
> support modules namespace

- spec/kemalyst-model_spec.cr
- src/kemalyst-model.cr
so you can just send it string values and don't have to do conversions in the controller.
```cr
p = Post.new
p.set_attributes(title: "auto casting saves time", description: "I love this feature",  tag_id: 35)
p.set_attributes({:title => "auto casting saves time", :description => "I love this feature",  :tag_id => 35})
```
I played around with tests but there don't seem to be any existing ones that work for this object. If you could get a couple base things working for testing the model I'll add some for this.
> added ability to cast to appropriate types within the model

- src/kemalyst-model.cr
* Post.create
accepts hash or namedtuple and returns a saved post model object.
* Post.new
accepts hash or namedtuple and returns unsaved object.
> new and create methods also work for casting to fields.

- spec/kemalyst-model_spec.cr
- spec/spec_helper.cr
- src/kemalyst-model.cr
Checked time string with regex to make sure that it contains a parseable string. Bool and Times can be passed as strings or Bool | Time.
> Fixed a couple issues with Bool and Time

- README.md
> Update fork url.

- src/granite_orm.cr
```crystal
require "granite_orm/adapter/pg"
class Post < Granite::ORM
adapter pg
before_save upcase_title # or :upcase_title
field title : String
field content : String
timestamps
def upcase_title
if title = @title
@title = title.upcase
end
end
end
```
- before_save
- before_create
- **save**
- after_create
- after_save
- before_save
- before_update
- **save**
- after_update
- after_save
- before_destroy
- **destroy**
- after_destroy
> add callbacks

- src/granite_orm.cr
Fixes this issue. https://github.com/amber-crystal/granite-orm/issues/44
> is/fixes issue with Time fields other than created_at and updated_at

- .env
- README.md
- spec/adapter/mysql_spec.cr
+ Generic database parameters
+ Database setup information
+ Fix MySQL error preventing tests from running
> Add documentation to README to get started with tests

- README.md
- spec/adapter/base_spec.cr
- src/adapter/base.cr
- src/adapter/mysql.cr
- src/adapter/pg.cr
- src/adapter/sqlite.cr
This change fixes the replacement of ENV variables.
It adds specs for the fixes.
I also cleaned out some old code that is not being used.
> fix environnment lookup.  add tests. clean out old code.

- README.md
- docs/index.html
- shard.yml
- src/granite_orm.cr
- src/granite_orm/base.cr
- src/granite_orm/error.cr
- src/granite_orm/transactions.cr
- src/granite_orm/validators.cr
Merge in Kemalyst validators and remove extra shard dependency.
> merge kemalyst validators

- README.md
- config/database.yml
- spec/adapter/mysql_spec.cr
- spec/adapter/pg_spec.cr
- spec/adapter/sqlite_spec.cr
- src/granite_orm/associations.cr
This addresses #59 and adds the ability to access a many-to-many relationship using a `through` option to the `has_many` macro.
> add support for has_many through

- README.md
Some code blocks weren't set as crystal code. This PR fix that.
> Add missing crystal highlighting

- README.md
This PR adds Docker testing instructions to the README.
> Docker Testing Instructions

- src/granite_orm/fields.cr
There were some missing places where DB::Any has to be replaced with
Type.
> Replaces DB::Any with Type

- src/granite_orm/fields.cr
This change merges the `cast_json_to_fields` and `cast_to_fields`.  It handles different scenarios including params being passed in as String or JSON::Type.  It also supports setting the types as their original declared type avoiding casting when not necessary.
This should allow for more flexibility to users so they can pass in what they have and as long as it can be converted, this will do its best to do so.
This should be backward compatible when someone passes in a Hash(String, String).
All existing specs pass.  Let me know if you think we should add more specific specs.
> refactor casting to support multiple types

- Dockerfile
update crystal version on docker image
> update crystal version on docker image

- src/granite_orm/fields.cr
> fixed #106 to_json

- spec/granite_orm_spec.cr
- src/granite_orm/validators.cr
> Fix validate block (#110)

- src/granite_orm/transactions.cr
> only rescue DB errors

- spec/granite_orm/fields/casting_spec.cr
- spec/granite_orm/transactions/save_spec.cr
- spec/spec_models.cr
- src/granite_orm/transactions.cr
> check if model is valid before trying to save

- README.md
> Fix documentation for creation of Indexes

- README.md
Hey @drujensen Thank you so much for granite!!! :+1: :smile: :clap: :sparkles: 
This PR updates links and code samples
> Update links and code samples

- README.md
- spec/granite_orm/associations/has_many_spec.cr
- spec/granite_orm/associations/has_many_through_spec.cr
- spec/granite_orm/fields/uuid_spec.cr
- spec/granite_orm/query/assembler/postgresql_spec.cr
- spec/granite_orm/query/builder_spec.cr
- spec/granite_orm/querying/from_sql_spec.cr
- spec/mocks/db_mock.cr
- spec/spec_models.cr
- src/granite_orm/association_collection.cr
- src/granite_orm/collection.cr
- src/granite_orm/query/assemblers/postgresql.cr
- src/granite_orm/query/builder.cr
- src/granite_orm/querying.cr
This PR addresses #174 by adding a spec for UUID creation.  I never really worked with UUIDs before so I'm not sure if there is anything more to test; other than it was created and is a String.
This PR also adds a UUID section to the README and cleans up some files using `crystal tool format`
> UUID Spec + Usage

- README.md
This PR changes old `Amber-Crystal` by new `amberframework`
> Update amber repository link

- README.md
- spec/granite/validations/validation_helpers_spec.cr
- src/granite/base.cr
- src/granite/validation_helpers.cr
This PR (#217) adds helper validators for common validations.
is_nil
not_nil
is_blank
not_blank
greater/less than (or equal to)
is valid choice
min/max length
It also adds a validation section to the readme
> Validation Helpers

- README.md
from crystal dep to shards install
> Fix wording on dep install

- src/granite/fields.cr
fixes https://github.com/amberframework/granite/issues/266
> Fix time parsing on Crystal 26.0

- docs/relationships.md
- spec/granite/associations/has_one_spec.cr
- spec/spec_models.cr
- src/granite/associations.cr
My first ever contribution to this wonderful project. And thanks to all the contributors for the awesome stuff that is Amber.
This PR adds `has_one` relationship to the models. Adds two simple methods which are documented and tested.
**NOTE:** It does not support through associations yet.
> Has one relationship

- Dockerfile
- src/granite/base.cr
> crystal 0.26.1 support

- spec/granite/transactions/touch_spec.cr
- spec/spec_models.cr
- src/granite/transactions.cr
> Implement #touch

- docs/relationships.md
This took me a few minutes to figure out so document it.
> docs/relationships.md: add example many to many insert

- docs/json_support.md
- docs/yaml_support.md
> document on_to_json/yaml

- Dockerfile
- shard.yml
- spec/granite_spec.cr
- src/granite/base.cr
- src/granite/fields.cr
- src/granite/version.cr
This fixes #337 the JSON serializers to support Crystal 0.29.0.  Thanks @bcardiff for your help.
> fixes for crystal 0.29.0

- docs/crud.md
> Update CRUD delete example code (#347)

- src/granite/fields.cr
Fix `undefined constant UUID` errors
> require "uuid" in fields.cr

- Dockerfile
- spec/granite/transactions/save_spec.cr
- spec/granite_spec.cr
- spec/spec_models.cr
- src/granite/columns.cr
- src/granite/error.cr
- src/granite/type.cr
- src/granite/validators.cr
> Handle string conversion & conversion errors

- spec/granite/transactions/update_spec.cr
- src/granite/columns.cr
> Allow #update to set column to nil

- shard.yml
- spec/granite_spec.cr
- src/adapter/base.cr
- src/granite.cr
- src/granite/association_collection.cr
- src/granite/query/executors/base.cr
- src/granite/settings.cr
- src/granite/transactions.cr
> Replace deprecated Logger via Log.

- spec/granite/table/table_spec.cr
- spec/spec_models.cr
- src/granite/table.cr
> Fix #394 by stripping the module name from the table name

- Dockerfile
- shard.yml
Minor changes needed to support 0.35.0
> Support Crystal 0.35.0

- spec/granite/querying/query_builder_spec.cr
- src/granite/query/builder.cr
> fix infinity loop

- src/granite/query/executors/base.cr
Fixes #423.
I'm thinking this is technically a breaking change since if someone had monitoring setup or something these would no longer be included within that.  99% it's not a big deal but 🤷.
> Lower log severity of query builder to make adapter
