amberframework/granite

Dockerfile
README.md
spec/adapter/mysql_spec.cr
spec/adapter/pg_spec.cr
spec/adapter/sqlite_spec.cr
spec/kemalyst-model_spec.cr
src/kemalyst-model.cr

@elorest @TechMagister I am introducing a breaking change to the models.  There is a new feature added to crystal that provides a `finished` macro to allow you to only process them at the end.
This allows us to have a model that looks like this:
```crystal
require "../src/adapter/mysql"
class Post < Kemalyst::Model
adapter mysql
field body : Text
field total : Int32
field draft : Bool
timestamps
end
```
thoughts?

use finished macro - breaking change

---

README.md
spec/adapter/mysql_spec.cr
spec/adapter/pg_spec.cr
spec/adapter/sqlite_spec.cr
src/adapter/pg.cr
src/granite_orm.cr

The goal of this PR is to add the `belongs_to` and `has_many` macros to Granite ORM Models to allow easier access to related data.
This addresses #30 
To Do:

One to many relationships

---

src/adapter/pg.cr
src/granite_orm/associations.cr
src/granite_orm/base.cr
src/granite_orm/fields.cr
src/granite_orm/validators.cr

Extract Associations from Fields

---

src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite_orm/associations.cr
src/granite_orm/base.cr
src/granite_orm/fields.cr
src/granite_orm/validators.cr

`db.query` fails when `params` is nil because `db.query` treats it as `[nil]`.
`__process` is not as long as before.
`JOIN` is not necessary because `{{foreign_key}}` is the same as `{{table_name}}.id`.
Just like other modules.
Then `.new`, `.create` and `#set_attribute` can be more flexible and convenient.

some minor changes

---

README.md

Text is only used in generators, not mapping
Addresses issue #60

fix types in examples

---

README.md

I found what appears to be a typo in the instructions while setting up my testing environment.
The instructions say to `$ export .env` where you'd actually use the `source` command to process the file with bash.

Readme Testing Instructions Fix

---

spec/granite_orm_spec.cr
src/granite_orm/fields.cr

This PR should satisfy the agreed upon resolution of #50 
It adds a `to_h` and `to_json` method to Granite ORM Models.

Add to_h and to_json to Granite::ORM::Fields

---

spec/granite_orm_spec.cr
src/granite_orm/fields.cr

This change ships two improvements:
1. Build json with [JSON::Builder](https://crystal-lang.org/api/0.23.1/JSON.html#build%28io%3AIO%2Cindent%3Dnil%2C%26block%29-class-method) is faster than `to_h.to_json` (because of transitional hash of course):
```crystal
require "benchmark"
require "./src/granite_orm"
require "./src/adapter/sqlite"
class Comment < Granite::ORM::Base
adapter sqlite
table_name post_comments
field body : String
end
s = "string"
c = Comment.new(name: s, body: s)
Benchmark.ips do |x|
x.report("to_h.to_json") do
c.to_h.to_json
end
x.report("JSON::Builder") do
c.to_json
end
end
```
```sh
$ DB_NAME=test.db crystal run example.cr --release …
```

Use JSON::Builder instead of to_h.to_json

---

src/granite_orm/base.cr
src/granite_orm/fields.cr

As a developer I want to be able to initialize a Granite Model from
Amber params
See PR https://github.com/amberframework/amber/pull/315
- Adds a Type alias
- Type includes  Hash(String, JSON::Type) | Array(JSON::Type)
- Adds Fields::Type to Base.cr initializer
With this change developers will be able to populate Model objects from
Amber params.validation results.

Adds  Support For Amber

---

spec/granite_orm_spec.cr
src/granite_orm/fields.cr

This change adds primary key to the result of `to_json` and `to_h`:
```crystal
class User < Granite::ORM::Base
adapter mysql
field email : String
timestamps
end
u = User.new(email: "user1@mail.com", name: "Hero").tap &.save
u.to_json #=> {"id":13,"email":"user1@mail.com","name":"Hero","created_at":"2017-10-18 19:02:18","updated_at":"2017-10-18 19:02:18"}
```
I think `id` (or other custom primary key) is an important attribute especially while creating an API. At any moment developer is able to select/reject attributes:
```crystal
u.to_h.select %w(email name)               #=> {"email" => "user1@mail.com", "name" => "Hero"}
u.to_h.reject %w(id created_at updated_at) #=> {"email" => "user1@mail.com", "name" => "Hero"}
```

Add primary key to json and hash

---

src/granite_orm/fields.cr

Removes Array(JSON::Type) and Hash(String, JSON::Type) since JSON::Type also represent the same.

Cleanup for JSON::Type

---

spec/granite_orm_spec.cr
src/granite_orm/base.cr
src/granite_orm/fields.cr

While testing the Amber master branch we found that there is an error
when passing a JSON::Type to a model.
This corrects that by adding a cast_json_to_field method that take in a
JSON::Type and asserts it to the correct type.
Backwards maintanability when using a Hash of string values or DB::Any.

Adds Cast From JSON::Type Support

---

spec/adapter/mysql_spec.cr
spec/adapter/pg_spec.cr
spec/adapter/sqlite_spec.cr
spec/granite_orm/querying_spec.cr
src/adapter/pg.cr
src/granite_orm/querying.cr

I'm unsure if this is in the spirit of this project or not, so I wanted to put some code out there and start a discussion before investing enough time to complete the algorithm and write specs.
`.all` is a fine way to deal with a couple hundred or so rows in a table, but above that it becomes a performance risk. ActiveRecord provides a nice way to get around this problem by fetching N rows from the database at once, and iterating over them in step. `find_each` iterates individual records and `find_in_batches` iterates batches as arrays of records. I consider this pattern essential for large datasets.
I noticed that there aren't any tests around the existing finders, which might mean that I'd struggle to set an acceptable spec pattern for these finders.
Assuming that these functions are a …

Provide find_in_batches and find_each

---

spec/adapter/mysql_spec.cr
spec/adapter/pg_spec.cr
src/granite_orm/transactions.cr

fixes #95 
This does not bring the mysql adapter into parity with postgresql because the mysql adapter returns `Time::Kind::Unspecified` instead of `Time::Kind::Utc`, however as the tests illustrate, the ticks behind the timestamp are correct.
Postgresql was the closest to consistent already, so this seems to make postgresql timestamps work as expected.
Sqlite is not addressed because of #29

forces timestamps to be in UTC

---

spec/spec_helper.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite_orm/settings.cr

This makes room for Granite to log queries to a logger. Hopefully it can then be integrated with Amber Logger. This will be especially helpful for prototyping changes to the ORM. I've had the basics of this code in a stash for several months and it's been very handy when experimenting with the ORM.
One of the more useful features of Rails is the transparent logging of database queries. Hopefully this can provide similar utility.
My initial stab at integrating this with the Amber logger required no changes beyond adding this line to the `initializers/granite.cr`:
```crystal
Granite::ORM.settings.logger = Amber.settings.logger
```
However, that leaves the log output a little less clean that desired. Nevertheless I believe the integration with Amber::Logger will be straightforward.
Comments …

Query logger

---

README.md

Hi, I understand that amber badges are centered, but I think we should keep this one left aligned
I think these look better:
Than this:

Make CI badge left aligned

---

spec/granite_orm/fields/casting_spec.cr
spec/spec_models.cr
src/granite_orm/error.cr
src/granite_orm/fields.cr

This change catches any casting errors and adds it to the `errors` instead of throwing an exception.  It addresses issue #99

add error if casting fails

---

spec/granite_orm/fields/casting_spec.cr
spec/spec_models.cr
src/granite_orm/fields.cr

avoid empty case statement

---

spec/granite_orm/table/table_spec.cr
src/granite_orm/table.cr

This fixes the original issue #76 with naming convention for tables that @marksiemers suggested

underscore instead of downcase

---

spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/transactions/save_spec.cr
spec/spec_models.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite_orm/querying.cr
src/granite_orm/table.cr

An SQL syntax error occurred using reserved keywords for column names such as `key`,` all`, and so on.
```sql
... WHERE key=?
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to
your MySQL server version for the right syntax to use near 'key=?' at line 1
```
This PR provides a quoting feature for table names and column names.
```sql
SELECT `kvs`.`id`, `kvs`.`key`, `kvs`.`value` FROM `kvs` WHERE `key`=? LIMIT 1;
INSERT INTO `select` (`all`) VALUES (?);
```
Best regards,

allow reserved words as table and column names

---

spec/granite_orm/fields/timestamps_spec.cr
spec/granite_orm/transactions/save_spec.cr
src/granite_orm/associations.cr
src/granite_orm/fields.cr
src/granite_orm/table.cr

In this PR, field requires values ​​by default, otherwise raises the proper missing exceptions.
Now, users can avoid the redundant `not_nil!`, and also can use `foo?` for the nilable cases.
```crystal
user = User.new(name: "maiha")
user.name? # => "maiha"
user.name  # => "maiha"
user = User.new
user.name? # => nil
user.name  # => User#name cannot be nil (Exception)
```
Best regards,

Fields are now required in default. Use `foo?` for nilable fields.

---

spec/granite_orm/associations/belongs_to_spec.cr
spec/granite_orm/associations/has_many_spec.cr
spec/granite_orm/fields/casting_spec.cr
spec/granite_orm/fields/timestamps_spec.cr
spec/granite_orm/querying/all_spec.cr
spec/granite_orm/querying/count_spec.cr
spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/querying/find_each_spec.cr
spec/granite_orm/querying/find_in_batches.cr
spec/granite_orm/querying/find_spec.cr
spec/granite_orm/querying/first_spec.cr
spec/granite_orm/transactions/destroy_spec.cr
spec/granite_orm/transactions/save_spec.cr
spec/spec_helper.cr
spec/spec_models.cr

In current specs, it seems **adapter name** will be embedded in many places by macro in order to avoid class name conflict between three adapters.
This PR uses modules like `Pg`, `Mysql`, `Sqlite` to avoid the conflict, and keeps model and db schema simple by removing macro variables like xxx_constant, xxx_suffix, xxx_table, xxx_literal from spec codes.
```crystal
adapter_const_suffix = adapter.camelcase.id
adapter_suffix = "_#{adapter.id}".id
parent_table = "parent_#{adapter_literal}s".id
class Parent{{ adapter_const_suffix }} < Granite::ORM::Base
table_name "{{ parent_table }}"
has_many :student_{{ adapter_literal }}s
parent_constant = "Parent#{adapter.camelcase.id}".id
all = {{ parent_constant }}.all
```
```crystal
module {{adapter.capitalize.id}}
class Parent < Granite::ORM::Base …
```

simplify specs by reducing macros

---

README.md
spec/granite_orm/fields/timestamps_spec.cr
spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/querying/find_spec.cr
spec/granite_orm/querying/first_spec.cr
spec/granite_orm/transactions/destroy_spec.cr
spec/granite_orm/transactions/save_spec.cr
src/granite_orm/querying.cr

This PR make class query methods to ensure a value exist in default like #144.
- `find`, `find_by`, `first` return `T` if exists, otherwise raises `NotFound`
- `find?`, `find_by?`, `first?` return `T?`
```crystal
User.find?(1) # => #<User:0x99a300 @id=1 ...
User.find(1)  # => #<User:0x99a300 @id=1 ...
User.find?(0) # => nil
User.find(0)  # raises Granite::ORM::Querying::NotFound.new("Couldn't find User with id=0")
```
This removes many `not_nil!` codes as in this commit.
Also this prevents newbies from asking 
- why undefined method 'xxx' for Nil?

`find`,`find_by`,`first` now ensures `T`, call with trailing `?` for `T?`

---

spec/granite_orm/callbacks/callbacks_spec.cr
spec/spec_models.cr

https://github.com/amberframework/granite-orm/pull/153#discussion_r170689455
> an exception thrown in a hook will get swallowed
This PR explicitly specifies why `DB::Error` is rescued in `#save`. After this PR, we can detect #153 is well regressed. 😄 
In addition, this also ensures the callbacks are fired and its order.
Best regard,

add spec for callbacks

---

spec/granite_orm/querying/all_spec.cr
spec/granite_orm/querying/count_spec.cr
spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/querying/find_each_spec.cr
spec/granite_orm/querying/find_spec.cr
spec/granite_orm/querying/first_spec.cr
spec/granite_orm/transactions/destroy_spec.cr
spec/granite_orm/transactions/save_spec.cr
spec/spec_models.cr
src/granite_orm/querying.cr
src/granite_orm/transactions.cr

This PR adds following three statuses to a record.
- `new_record?`, `destroyed?`, `persisted?`
| code         | new_record?           | destroyed?            | persisted?            |
|--------------|-----------------------|-----------------------|-----------------------|
| User.new     | :white_check_mark:    | :white_large_square: | :white_large_square:    |
| user.save    | :white_large_square: | :white_large_square: | :white_check_mark:    |
| user.destroy | :white_large_square: | :white_check_mark:    | :white_large_square: |
| User.find    | :white_large_square: | :white_large_square: | :white_check_mark:    |
In addition, now we can put any value for the primary key if we want. 
This solves `INSERT` problem in #143 and will also help introduce natural keys.
```crystal
user = …
```

add record statuses about persistence: `new_record?`, `destroyed?`, `persisted?`

---

spec/granite_orm/querying/all_spec.cr
spec/granite_orm/querying/count_spec.cr
spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/querying/find_each_spec.cr
spec/granite_orm/querying/first_spec.cr
spec/granite_orm/transactions/save_spec.cr
spec/spec_models.cr

In current specs, every time we run one test case, we initialize 33 tables with 3 adapters in total. 
```crystal
Spec.before_each do
adapters.each do |adapter| # 3 times
adapter::table1.clear    # 11 tables in total
...
```
This is **expensive** to run and is **unnecessary** work for most test cases. Therefore, execution of all tests is very slow and this cost will continue to increase each time additional functionality is added.
In this PR, I propose a policy to delete tables **manually** rather than **automatically**. When writing a test, we do not assume that the table is empty, we need to manually run the table as needed.
In my environment.
- `8m13s` (with 6118 DB operations)
- `43s` (with 1012 DB operations)
FYI: This is a commits dependency for natural-key in my fork.
1. #154 add …

spec: don't clear database automatically

---

spec/granite_orm/transactions/create_spec.cr
src/granite_orm/base.cr
src/granite_orm/transactions.cr

From commit history, this looks like regression after extracting some modules.
Example usage:
```
parent = Parent.create(name: "Test Parent")
```
or (more useful example)
```
params = { name: "Test Parent" }.to_h
parent = Parent.create(params)
```
instead of 
```
parent = Parent.new
parent.name = "Test Parent"
parent.save
```

Fix .create class method

---

README.md
spec/granite_orm/fields/primary_key_spec.cr
spec/granite_orm/transactions/save_natural_key_spec.cr
spec/spec_models.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite_orm/fields.cr
src/granite_orm/table.cr
src/granite_orm/transactions.cr

This PR enhances `Model.primary` to accept `auto` option that works as a natural key if false.
```
mysql> DESCRIBE kvss;
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| k     | varchar(255) | NO   | PRI | NULL    |       |
| v     | varchar(255) | YES  |     | NULL    |       |
+-------+--------------+------+-----+---------+-------+
```
```crystal
class Kvs < Granite::ORM::Base
adapter mysql
primary k : String
field   v : String
end
```
First, if you use a primary key other than Int as described above, it will give a compile error with following suggestion.
```crystal
Failed to define Kvs#save: Primary key must be Int(32|64), or set `auto: false` for natural keys. …
```

Supporting natural keys

---

spec/spec_models.cr
src/granite_orm/querying.cr

A quick simple fix to handle created_at/updated_at when using sqlite database adapter, however the values must be populated (which should be the case if the timestamps settings value has been enabled)

parse timestamp strings for sqlite db adapter

---

spec/granite_orm/associations/belongs_to_custom_type_spec.cr
spec/spec_models.cr
src/granite_orm/associations.cr

This allows you to specify a custom name and type for the `belongs_to` foreign key.   I needed this for backward compatibility with a rails project that has Int(11) in mysql.
```
belongs_to :tool, tool_id : Int32
```
This does not address the `has_many` relationship.

add belongs_to custom type support

---

src/granite_orm/fields.cr
src/granite_orm/querying.cr
src/granite_orm/transactions.cr

In master, when we want to iterate all fields, we have to process three kinds of fields **pk**, **content columns** and **timestamps** as following code. I feel this is a boring work and the code looks difficult.
```crystal
def to_xxx
{{ PRIMARY[:name] }}
{% for name, type in FIELDS %}
...
{% if SETTINGS[:timestamps] %}
```
This PR merges them into one FIELDS, and the `primary` and `timestamp` now becomes just wrapper macros to the `field`. Thus, we can simply iterate `FIELDS` to scan all fields.
```crystal
def to_xxx
{% for name, type in FIELDS %}
...
```
- added `CONTENT_FIELDS` that removes **PK** from `FIELDS`
- added `Base.fields` to provide cached field names.
- added `Base.content_fields` to provide cached content field names.
- renamed `Base#params` to `Base#content_values` for …

refactor: Unify pk and content and timestamps into `FIELDS`

---

README.md
spec/granite_orm/callbacks/callbacks_spec.cr
spec/granite_orm/fields/primary_key_spec.cr
spec/granite_orm/fields/timestamps_spec.cr
spec/granite_orm/querying/find_by_spec.cr
spec/granite_orm/querying/find_spec.cr
spec/granite_orm/querying/first_spec.cr
spec/granite_orm/transactions/create_spec.cr
spec/granite_orm/transactions/destroy_spec.cr
spec/granite_orm/transactions/save_natural_key_spec.cr
spec/granite_orm/transactions/save_spec.cr
src/granite_orm/associations.cr
src/granite_orm/fields.cr
src/granite_orm/querying.cr
src/granite_orm/table.cr

I made this change because the previous syntax was a major breaking change that
is not compatible with the Amber templates.  This accomplishes the same thing
but changes the default to be nilable and adds a bang version for `.not_nil!` equivalent.
This will allow us to avoid changing the Amber templates and is backward compatible so we don't break a bunch of peoples existing websites.
Its always recommended to check and see if a `first`, `find`, or `find_by` returns results but if you are absolutely sure you know the results will return, you can use the simpler `first!`, `find!`, or `find_by!` which will throw a runtime exception.
Same with fields, its best to check for `nil` values but if you are absolutely sure the value is not nil, then you can use the simpler `!` version of the field. …

changes syntax for helper methods from ? to !

---

README.md

Ref: [#173 (comment)](https://github.com/amberframework/granite/pull/173/files#r178588297)

Revert code samples until ORM word is removed

---

spec/granite_orm/fields/field_spec.cr
src/granite_orm/fields.cr
src/granite_orm/querying.cr
src/granite_orm/table.cr

relate: #57, #120, #144, #171
This PR supports the two syntaxes in #171 by #57.
For example:
```crystal
class Foo < Granite::ORM::Base
field number : Int32
end
foo = Foo.new(number: 0)
foo.number += 1
```
This gives:
```
Error in src/test.cr:7: undefined method '+' for Nil (compile-time type is (Int32 | Nil))
foo.number += 1
^
Rerun with --error-trace to show a complete error trace.
```
It is still annoying to use `foo.number = foo.number! + 1`.
With this PR:
```crystal
class Foo < Granite::ORM::Base
field! number : Int32
end
foo = Foo.new(number: 0)
foo.number += 1 # It works!
```
This PR also includes the change from `type` to `options` in #120 because it is easier to implement `field!` with this feature.
This PR also removes the property in `table.cr` because it is duplicated.

Add field! for property!

---

spec/granite_orm/associations/has_many_spec.cr
spec/granite_orm/associations/has_many_through_spec.cr
src/granite_orm/association_collection.cr
src/granite_orm/associations.cr
src/granite_orm/base.cr
src/granite_orm/collection.cr
src/granite_orm/querying.cr

My proposal for lazy loaded collections. 
Now using `.all` method queries database immediately, after this change it would return a `Granite::ORM::Collection(Model)` which forwards missing methods to the array of records.
```
Klass.all # queries database [Klass1, Klass2]
Klass.all # does not query => Granite::ORM::Collection(Klass)
Klass.all.each do |klass| # queries db
end
```
Now using `has_many` association methods, loads all related records from the database. After this change, it would return a `Granite::ORM::AssociationCollection(Owner, Target)`. This allows easy extensions on associations (for example https://github.com/amberframework/granite/issues/121 should be easy to implement as `association.delete_all`). Included `find_by` and `all` as an example for this.
```
student.klasss …
```

Change .all and has_many to return *Collection object

---

spec/granite_orm/callbacks/abort_spec.cr
spec/spec_models.cr
src/granite_orm/callbacks.cr
src/granite_orm/transactions.cr

A long time ago(maybe a few months), someone asked me how to abort a transaction within a callback in Amber's Gitter.
I did say that you can't, but now the feature is implemented.
Example:
```crystal
class Foo < Granite::ORM::Base
before_create do
abort! if some_condition
end
end
```
I don't know why I missed this in my previous PR #56.
Example:
```crystal
class Foo < Granite::ORM::Base
before_save method_a, method_b
end
```
This is convenient when the callback is simple.
The first example is also an example of this.
Because `#abort!` in `after_create` or `after_destroy` doesn't abort the main transaction, but it would abort the update of `@new_record` and `@destroyed` before.

Some enhancements about callbacks

---

Dockerfile

Updates Dockerfile to use crystal `0.24.2`

Use most recent version in granite docker image

---

README.md

I forgot to update README with usage of using manually trigger callbacks with `.import` so here it is.

Update README for manually running callbacks

---

README.md
spec/spec_models.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite_orm/base.cr
src/granite_orm/migrator.cr

Dry up codes about creating tables in specs, and put it production code as `Granite::ORM.migrator`.
This helps users
- to add tables in specs easily
- to create tables in experiment and deployment
```crystal
class User < Granite::ORM::Base
adapter mysql
end
User.migrator.create
```
```
mysql> describe users;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
```
- mapping rules from **crystal class** to **database type** is defined in …

Fixes to Migrator provided by Maiha

---

src/granite_orm/callbacks.cr
src/granite_orm/transactions.cr

This removes one level of abstraction and removes the `_run_` from the macros.

remove extra abstraction and _run_

---

README.md
spec/granite/associations/has_many_spec.cr
spec/granite/associations/has_many_through_spec.cr
spec/granite/fields/timestamps_spec.cr
spec/granite/querying/find_by_spec.cr
spec/granite/querying/find_spec.cr
spec/granite/querying/first_spec.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/association_collection.cr
src/granite/querying.cr

This PR (#206) allows `find_by` and `find_by!` to accept multiple criteria.
This does change the syntax of the method, but i think this is a better solution long term than having two different methods with different syntaxes for each.
This touches a fair bit of the `querying.cr` since `find` was wrapping `find_by`, and since you cannot declare a dynamic keyed NamedTuple to pass to the new `find_by` I had to replace it with `first`
fixes #206

Allow `find_by` to accept multiple arguments

---

spec/granite/transactions/create_spec.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/granite/transactions.cr

First of all, thanks for the great library!
While working on an application using Granite we noticed a race condition with the IDs being returned for instances. In our case, it was two concurrent API requests to a create API - both records were being returned with the same ID.
The failing spec I've added here is a minimal example to reproduce the issue. We discovered it using postgres but it also appears to occur for mysql. I've included fixes for both adapters.
Strangely, the issue doesn't seem to occur with sqlite any time I have run the specs. I'm not sure if this is coincidence, or if some difference in the driver prevents the fiber from yielding in the same way. For now I've left the adapter untouched, but it may be more correct to wrap it in a `using_connection` block the same way I …

Fix last insert ID race condition

---

README.md
spec/granite/select/select_spec.cr
spec/spec_models.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/base.cr
src/granite/querying.cr
src/granite/select.cr

This PR (#184 & #200) allows you to customize the SQL used in the SELECT portion of the query (or the entire query if necessary) by adding the `query` macro.
The major limitation is that when using a highly-modified `query`, the save/update functionality of the model will likely break.  In the issue @drujensen suggested taking a more complete View Model approach, and I agree with that entirely, but wanted to start with a slightly narrower scope.  So this is "View Model Lite".  Baby steps.  Likewise, `find` may also break depending on how the query is modified.
Also, naming is hard.  I'm not wedded to any of the names used, and particularly with things like Query, Select, etc., things might get complex.
(PS - Please feel free to rip to shreds :) I'm new to this type of contribution so am …

added query macro, tests, and docs

---

README.md
spec/granite/transactions/create_spec.cr
spec/granite_spec.cr
src/granite/base.cr
src/granite/error.cr
src/granite/fields.cr
src/granite/transactions.cr

This PR resolves #170 by including support for model.new(JSON::Any)
I just added another layer of ternary that checks of the value is of the `JSON::Any` type, if it is then use the `JSON::Any` .as_x to cast it to proper type.

Support model.from_json(JSON::Any)

---

src/granite/query/executors/base.cr

The querybuilder as is doesn't work and isn't usable because the logger call isn't working, resulting in this error message:
```
in lib/granite/src/granite/query/executors/base.cr:8: undefined constant Granite::Logger
Granite::Logger.log messages
^~~~~~~~~~~~~~~
```
This corrects the showstopping bug, and lets this appear in the logs instead:
The log formatting still needs a bit of work, but at least it _compiles_
🍌

bugfix: querybuilder logger

---

README.md
spec/granite/validations/validation_helpers_spec.cr
src/granite/validation_helpers.cr

<h1>What is done</h1>
- Added a new macro "validate_uniqueness" with one parameter called "field"
- Added test to verify behaviour
- Added documentation
<h1>Explaination</h1>
The validator add a feature to the validator helpers that verify if the field value is not already in use. The validator will try to fetch one record that has the same field value. If the value does not exist in the database than the validation will succeed. If the value does exist in the database it will fail if the record is not the same as the model that is being updated.

Added uniqueness validator for models

---

Dockerfile
shard.yml
spec/granite/fields/timestamps_spec.cr
spec/granite/querying/find_by_spec.cr
spec/granite/querying/from_sql_spec.cr
spec/granite_spec.cr
src/granite.cr
src/granite/base.cr
src/granite/fields.cr
src/granite/querying.cr
src/granite/transactions.cr

Minimally addresses issues required to update Granite to Crystal 0.25.0
Read the changelog for anything I missed. https://github.com/bcardiff/crystal/blob/changelog/0.25.0/CHANGELOG.md
Fixes #226

Update to crystal 0.25.0

---

shard.yml
spec/granite/fields/timestamps_spec.cr
spec/granite/querying/from_sql_spec.cr
spec/granite/transactions/import_spec.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/base.cr
src/granite/fields.cr
src/granite/querying.cr
src/granite/transactions.cr

The latest granite tag produces this when attempting to build amber projects which used the scaffold generator:
```
instantiating 'PostCommentController#create()'
in src/controllers/post_comment_controller.cr:22: no overload matches 'PostComment.new' with type Hash(String, String | Nil)
Overloads are:
- Granite::Base.new(args : Hash(Symbol | String, String | JSON::Any))
- Granite::Base.new(**args : Object)
- Granite::Base.new()
post_comment = PostComment.new(post_comment_params.validate!)
```
In trying to get the amber project compatible with crystal 0.25, I'd like to change this to JSON::Any::Type, which allows the generated code to compile.

Further update Granite to be compatible with Crystal 0.25

---

README.md
spec/granite/exceptions/record_invalid_spec.cr
spec/granite/exceptions/record_not_destroyed_spec.cr
spec/granite/transactions/create_spec.cr
spec/granite/transactions/destroy_spec.cr
spec/granite/transactions/save_spec.cr
spec/granite/transactions/update_spec.cr
spec/spec_models.cr
src/granite/exceptions.cr
src/granite/transactions.cr

<h1>What is done</h1>
Added "helper" methods that raises exceptions on errors. The idea is that sometimes you want to be sure that an transaction method has succeeded. If the method did not complete successfully than it will raise an exception.
<h1>Methods</h1>
- Added update method that accepts args that will set the attributes of the model and tries to save it
- Added update! method that accepts args that will set the attribute of the model and tries to save! it
- Added save! method that will call the save method and raises an exception if it failed
- Added create! method that will call the create method and raises an exception if it failed
- Added destroy! method that will call the destroy method and raises an exception if it failed
- Added custom exceptions for the methods so an …

Adding transaction raise methods

---

README.md
spec/granite/querying/passthrough_spec.cr
spec/spec_models.cr
src/granite/select.cr

renamed the macro to `select_statement` so it won't conflict with the pass-through `query` method.  fixed #246

fix conflicting use of query

---

Dockerfile
README.md
spec/granite/transactions/create_spec.cr
spec/granite_spec.cr
spec/spec_models.cr
src/granite/base.cr
src/granite/callbacks.cr
src/granite/error.cr
src/granite/fields.cr
src/granite/transactions.cr
src/granite/validators.cr

This PR, fixes #253 brings about native support for JSON::Serializable.  This is super exciting and probably my favorite PR so far.  The benefits of this are immense, especially when working with JSON APIs.
```Crystal
class Foo < Granite::Base
adapter mysql
table_name foos
field age : Int32
end
```
`foo = Foo.from_json(%({"name": "Granite", "age": 10})) `
```Crystal 
<Foo:0x55c77d901ea0
@_current_callback=nil,
@age=10,
@created_at=nil,
@destroyed=false,
@errors=[],
@id=nil,
@name="Granite",
@new_record=true,
@updated_at=nil>
```
`foo.to_json`
```JSON
{
"name": "Granite",
"age": 10
}
```
`foo = Array(Foo).from_json(%([{"name": "Granite1", "age": 10},{"name": "Granite2", "age": 50}]))`
```Crystal
[#<Foo:0x55f66bdeaea0
@_current_callback=nil,
@age=10,
@created_at=nil, …
```

Support JSON::Serializable

---

docs/getting_started.md
src/granite/callbacks.cr
src/granite/fields.cr
src/granite/migrator.cr
src/granite/querying.cr
src/granite/table.cr
src/granite/transactions.cr
src/granite/validators.cr

This PR resolves #251.
It provides the ability to skip generation of Granite methods, macros, constants etc when using `crystal docs`.  It will only _not_ include the docs when the ENV var `DISABLE_GRANITE_DOCS=true`, if it is not set, or set to false it will include the Granite stuff.
The reasoning behind this; before this change on a just primary key model:
There is so much here that it almost makes the docs for the user's project unusable.
The same model skipping Granite stuff:
As you may notice this also adds the ability to define a comment to use on the getter/setter of each property with the following syntax: 
`field name : String, comment: "# The name of person"`
or in this case:
`primary id : Int64, comment: "# The primary key"`

Optionally add nodoc

---

src/granite/fields.cr

Missed this logic when adding JSON::Serializable support.

Revert `.is_a?(JSON::Any)`

---

docs/relationships.md

The "through class" when defining a has_many through: association needs to be written as a symbol.

Make the "through class" a symbol

---

docs/relationships.md

an example of that when it is necessary to establish foreign_key instead of default Int64 on String

Example for String foreign_key

---

spec/granite/validations/validator_spec.cr
src/granite/validators.cr

Currently validation checking is not independent and errors are left over from previous checks.
```
model.name = ""
model.valid? # => false, fails on validation for presence
name.name = "name"
model.valid? # => false, fails because errors are left over from previous validation
```
After this change validation checks clear previous errors before running the associated validators to add errors back onto the model.
```
model.name = ""
model.valid? # => false, fails on validation for presence
name.name = "name"
model.valid? # => true
```
This is not particularly useful for production code, but allows for more flexibility in specs.

Clear errors before validating models

---

docs/getting_started.md
spec/granite/fields/uuid_spec.cr
spec/spec_models.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/fields.cr
src/granite/migrator.cr
src/granite/table.cr
src/granite/transactions.cr

Resolves #210 
Allows the primary macro's `auto` to take a `:uuid` option.  This will generate a secure UUID on model save.  
This is compliant with all three adapters, with MySQL and SQLite using `char(36)` datatype for migrator, while Postgres uses its native `UUID` type.

Better UUID support

---

spec/granite/query/builder_spec.cr
src/granite/query/assemblers/base.cr
src/granite/query/builder.cr

This adds two new methods: `and` and `or`.  
```crystal
User.where(age: 24).and(gender: "male").and(:name, :like, "joe*").or(:name, :like, "fred*")
```
The where method was modified to generate the where SQL with appropriate clauses.  Let me know if you think there is a better way to do this.
I will add specs soon.

Add support for AND and OR clause

---

spec/granite/query/spec_helper.cr
src/granite/query/assemblers/base.cr

`Assembler#count` appends `ORDER BY id DESC` to sql unintentionally since #284.
Sorry for making this bug and here is the fix.

Fix Assembler#count

---

spec/granite_spec.cr
spec/spec_models.cr
src/granite/transactions.cr

Adds specs for the `json_options` and `yaml_options` features
Also only includes `@updated_at` and `@created_at` properties if they were added via the `field` or `timestamps` macros.
This _could_ break people's apps who were using those without declaring them, maybe?  But i doubt it.

Only define `updated/created_at` properties if they are wanted

---

spec/granite/associations/belongs_to_spec.cr
spec/granite/associations/has_many_spec.cr
spec/granite/associations/has_one_spec.cr
spec/spec_models.cr
src/granite/association_collection.cr
src/granite/associations.cr
src/granite/fields.cr
src/granite/transactions.cr

* Allows custom primary keys on `belongs_to` and `has_one` associations. 
* Adds bang, raise on nil, methods to `belongs_to` and `has_one` associations. 
* Makes the `has_many` association use whatever primary key is defined on the model, vs always assuming `id`

Association improvements

---

spec/granite/fields/casting_spec.cr
spec/granite/fields/timestamps_spec.cr
spec/spec_helper.cr
src/granite.cr
src/granite/fields.cr
src/granite/querying.cr
src/granite/settings.cr
src/granite/transactions.cr

Add timezone support to set and get value with `Time` type, but the row in database is still UTC, because [sqlite](https://github.com/crystal-lang/crystal-sqlite3/blob/master/src/sqlite3.cr#L8) and [mysql](https://github.com/crystal-lang/crystal-mysql/blob/master/src/mysql.cr#L16) shards defined a constant  `TIME_ZONE` use `Time::Location::UTC`
Add `default_timezone` property to `Granite::Settings`. setter accepts two types of value: `Time::Location` and `String` but getter returns a `Time::Location` type.
Example:
```crystal
Grante.settings.default_timezone = Time::Location.local
Grante.settings.default_timezone = "Asia/Shanghai"
```

Add timezone support

---

spec/granite/fields/field_spec.cr
spec/granite/query/assemblers/mysql_spec.cr
spec/granite/query/assemblers/pg_spec.cr
spec/granite/query/assemblers/sqlite_spec.cr
spec/granite/query/builder_spec.cr
spec/granite/querying/query_builder_spec.cr
spec/granite_spec.cr
spec/spec_models.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/fields.cr
src/granite/query/assemblers/base.cr
src/granite/query/assemblers/mysql.cr
src/granite/query/assemblers/pg.cr
src/granite/query/assemblers/sqlite.cr
src/granite/query/builder.cr
src/granite/query/executors/list.cr
src/granite/query/executors/value.cr

Allows for the query builder to handle params that are arrays.  It auto casts them to an `:in` query.
```
Courier.where(date_completed: nil, status: ["outstanding", "in_progress"]).select
SELECT contract_id, status, date_completed FROM couriers WHERE date_completed IS NULL AND status IN ('outstanding','in_progress') ORDER BY contract_id DESC
```
I had some trouble using placeholder vars in this context.  Both `["('outstanding','in_progress')"]` and `[["outstanding", "in_progress"]]` caused a syntax error.  To get around this i just build out the IN statement and plop in the value into the query.  Any ideas on how to better handle this?

Support array IN queries with query builder

---

src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/query/executors/base.cr
src/granite/settings.cr
src/granite/transactions.cr

Adds color and execution time to logged queries.
Totally steals the humanize duration from @robacarp's mosquito lib :wink: 
Can ignore everything up to the execution time, everything else is because im running in docker and mosquito.
SELECT:
INSERT:
With Numbers:

Add colors to logged queries

---

docs/getting_started.md
spec/granite_spec.cr
spec/spec_models.cr
src/adapter/base.cr
src/granite/fields.cr

Adds the ability to define default values.  Changes `#quote` to use `String.build` vs `#gsub` and `+`.  
```
quote   9.23M (108.35ns) (± 3.16%)  256 B/op   1.60× slower
string builder   14.8M ( 67.58ns) (± 1.12%)  208 B/op        fastest
```

Support default values

---

spec/granite_spec.cr
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/settings.cr
src/granite/transactions.cr

@Rx14 brought to my attention a better way to implement the feature where logging doesnt run if the logger's io is nil.
https://github.com/amberframework/granite/compare/master...Blacksmoke16:logger-optimization?expand=1#diff-094e647002b88e121bcba1392f8416a8R34
Since we are calling the `colorize` method inside the block of `Granite.settings.logger.debug`, it will return before executing `colorize` if the IO is set to nil.  Because of this, I was able to reset the logger's type to `Logger`, and revert the nil checks i was doing.  Also because of this https://github.com/amberframework/amber/pull/1027 can be reverted once this is released.

Logger optimization

---

Dockerfile
spec/granite/fields/field_spec.cr
src/granite/fields.cr

Now that https://github.com/crystal-lang/crystal/pull/7330 is merged and released, we should probably raise a `NilAssertionError` to be consistent.

Raise NilAssertionError on nil value

---

Dockerfile
spec/granite/transactions/update_spec.cr
src/granite/transactions.cr

This PR makes it so that when updating a record (that has a valid ID and `new_record = false`), with a `nil` `created_at`, it should not update the `created_at` field in the DB.
I noticed this (and the PRs before this) while working on my blog/tutorial post.  Where I was working on updating an object from the JSON PUT body like:
```json
{
"id": 12,
"user_id": 7,
"title": "My Blog",
"body": "The Blog!",
"updated_at": "2019-02-23T15:32:03Z"
}
```
However, since `created_at` was not included, it was getting set to `nil`, which upon saving the record, was overriding the `created_at` column to be null.  Which, even if it _was_ set, it should not be included in the `UPDATE` query.
I also changed the `new_record` getter to a property.  The use case for this is so that external shards could add …

Do not update created_at on update

---

Dockerfile
spec/granite/table/table_spec.cr
src/granite/table.cr

Makes the `primary_type` method return the actual `.class` type of the primary key, versus a string.  Having the actual type is much more useful.

Make primary_type return the class type vs string

---

Dockerfile
LICENSE
docker-compose.yml
docs/json_support.md
docs/querying.md
docs/yaml_support.md
shard.yml
spec/granite/associations/belongs_to_spec.cr
spec/granite/fields/timestamps_spec.cr
spec/granite/querying/from_sql_spec.cr
spec/granite/transactions/touch_spec.cr
spec/granite/transactions/update_spec.cr
src/adapter/sqlite.cr
src/granite/querying.cr
src/granite/transactions.cr

* Updates Dockerfile to `0.28.0` for CI
* Updates deprecated references of `Time.utc_now` and `Time.now` (#329)
* Updates docker-compose file to show all deprecation warnings
* Also will error on something being deprecated.  I could go either way if we want CI to fail or not if something becomes deprecated.  Thoughts @drujensen @robacarp @amberframework/granite?

Some updates for Crystal 0.28.0

---

src/granite/fields.cr
src/granite/table.cr

Resolves #340 
```cr
...
in spec/spec_helper.cr:16: while requiring "./spec_models"
require "./spec_models"
^
in spec/spec_models.cr:8: The type of Teacher#id cannot be a Union.  The 'primary' macro declares the type as nilable by default.
{% begin %}
^
```
```cr
...
in spec/spec_helper.cr:16: while requiring "./spec_models"
require "./spec_models"
^
in spec/spec_models.cr:8: The type of Teacher#age cannot be a Union.  The 'field' macro declares they type as nilable by default.  Use the 'field!' macro to declare a not nilable field.
{% begin %}
```

Disallow union types

---

spec/granite_spec.cr
src/granite/querying.cr
src/granite/select.cr
src/granite/table.cr
src/granite/transactions.cr

I discovered this when working on another project.  The jist of it is when restricting an ivar to `Granite::Base`, the compiler will complain that
```cr
can't infer the type of class variable '@@primary_name' of Granite::Base.class
exec_exists "#{@@primary_name} = ?", [id]
```
I'm guessing that since we're operating on the class level and these class vars get set via the macro included/finished hooks, they are not set.  However using the class getters gets around that since their types are known and not reliant on the actual setting of the value.

replace @@var with their getter

---

.env
Dockerfile
README.md
docker-compose.yml
shard.yml
spec/granite/converters/uuid_spec.cr
spec/granite/query/spec_helper.cr
spec/mocks/db_mock.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/converters.cr

This is waiting for a mysql and pg driver releases

Crystal v0.30.0 changes

---

shard.yml
src/adapter/base.cr
src/adapter/mysql.cr
src/adapter/pg.cr
src/adapter/sqlite.cr
src/granite/query/assemblers/base.cr
src/granite/query/executors/list.cr
src/granite/query/executors/multi_value.cr
src/granite/query/executors/value.cr
src/granite/querying.cr

This PR updates micrate to latest crystal-db and bump drivers to compatible versions also.

Update to crystal-db ~> 0.7.0

---

spec/granite_spec.cr
spec/spec_models.cr
src/granite/columns.cr
src/granite/transactions.cr

Fix some compile error messages
**Issue:** https://github.com/amberframework/granite/issues/361
EDIT:  I should also mention this makes it so the type of the resulting hash now only consists of the types of the model's columns.  I.e. if a model does not define a `Time` column, then there wouldn't be `Time` in the type union.

Allow enums to be used within `#to_h`

---

spec/granite_spec.cr
spec/spec_models.cr
src/granite/columns.cr

Fixes #373
the previous `||` based logic for returning default values was flawed since `false` is a valid value but would cause the default to be returned.

Handle `false` when a column has a default value

---

src/granite/error.cr

Fix: Ensure `Granite::Error#to_s` returns string

---

spec/granite/columns/read_attribute_spec.cr
src/granite/columns.cr

Fix read_attribute, see #396

---

spec/granite/error/error_spec.cr
src/granite/error.cr

I wasn't sure if this was something that was at all wanted, so I figured I'd send a PR to be safe.
This PR manually defines a `to_json` method for `Granite::Error`. We can't `include JSON::Serializable` due to the type of `Granite::Error.field`, so a manual solution is required.

Add a to_json method for Granite::Error

---

docs/querying.md
spec/granite/query/assemblers/mysql_spec.cr
spec/granite/query/assemblers/pg_spec.cr
spec/granite/query/assemblers/sqlite_spec.cr
spec/granite/query/builder_spec.cr
src/granite/query/assemblers/base.cr
src/granite/query/assemblers/mysql.cr
src/granite/query/assemblers/pg.cr
src/granite/query/assemblers/sqlite.cr
src/granite/query/builder.cr

This is a first attempt at addressing #402 , and implements support for building simple queries through the use of handwritten SQL like so:
```
users = Users.where("age > ?", 18) # == where(:age, :gt, 18)
```
with the intention of providing a way to support more sophisticated queries, such as
```
users = User.where("LOWER(name) = ?", name)
```
and even database specific features, like checking for membership in an array using Postgres:
```
users = User.where("? = ANY(trusted)", id)
```
The current implementation only allows one argument per query, but it should be rather straightforward to extend this to allow multiple args per query, if that's desired.
A simple spec is included for each DB adapter.
Note: I've opened this PR as a draft because I also intend to include an addition to the …

Support custom queries in builder

---

src/granite/base.cr
src/granite/select.cr

Reboot of https://github.com/amberframework/granite/pull/345.  Was getting:
```
Showing last frame. Use --error-trace for full trace.
In lib/granite/src/granite/select.cr:19:5
19 | @@select
^
Error: can't infer the type of class variable '@@select' of Granite::Base.class
The type of a class variable, if not declared explicitly with
`@@select : Type`, is inferred from assignments to it across
the whole program.
...
Other assignments have no effect on its type.
can't infer the type of class variable '@@select' of Granite::Base.class
```
When working on some Athena stuff.

Define @@setter with `class_getter`

---

docs/querying.md
docs/relationships.md

CustomView Example,
```
1 | class CustomView < Granite:Base
^
Error: Granite is not a class, it's a module
```
Create Index was failing silently when used with `amber db migrate`
```
=# CREATE INDEX 'team_id_idx' ON coaches (team_id);
ERROR:  syntax error at or near "'team_id_idx'"
LINE 1: CREATE INDEX 'team_id_idx' ON coaches (team_id);
^
```
Signed-off-by: Aravinda Vishwanathapura <mail@aravindavk.in>

Documentation fixes for the following errors

---

spec/granite/transactions/save_spec.cr
src/granite/transactions.cr

This PR add an named argument to `#save` method which allow to disable model validation, example:
```crystal
class Example < Granite::Base
...
column name : String?
validate :name, "Name cannot be blank" do |parent|
!parent.name.to_s.blank?
end
...
end
new_instance = Example.new
new_instance.name = ""
new_instance.save(validate: false)
new_instance.persisted? #=> true
another_instance = Example.new
another_instance.name = ""
another_instance.save(validate: true)
another_instance.persisted? #=> false
```
No breaking changes and works as well with `#save!`

Added a way to disable validation on save method

---

src/granite/table.cr

This change changed the `table` and `adapter` macros to support both string and symbols.

Support symbols for table and adapter macros

---

docs/models.md
spec/granite/associations/belongs_to_spec.cr
spec/spec_models.cr
src/granite/associations.cr

Really simple change that allows the creation of `belongs_to` relationships in which the created `column` is the primary key for the table.

Add primary field to belongs_to relationships

---

spec/mocks/db_mock.cr

crystal-db does not include a type restriction. Since 1.0.0-dev is more strict with abstract methods this change is required to make the FakeConnection honor the current DB::Connection API
Maybe crystal-db should restrict the query to String since the DB::Statement now has a `@command : String`. That can come later in future releases while being backward compatible.
Ref: https://github.com/crystal-lang/crystal/pull/9634

Drop argument type restrictions in FakeConnection

---

spec/granite/migrator/migrator_spec.cr
src/granite/migrator.cr

The built-in Model.migrator.create_sql will create columns
with NOT NULL unless the types are in fact nullable.

Migrator: create columns with NOT NULL as appropriate

---

docs/migrations.md

According to #432, migrator should only be used for internal testing. Therefore, I changed the documentation accordingly.

Change documentation to prefer micrate

---

docs/migrations.md

As of at least Micrate 0.11.0, `bin/micrate create` doesn't create a migration file, it creates the database. `scaffold` is the command to create a migration file. This PR corrects this in the migration docs.
```bash
$ bin/micrate help
*snip*
Commands:
create     Create the database (permissions required)
*snip*
scaffold   Create the scaffolding for a new migration
```

Fix command to create a migration to `scaffold`

---

spec/mocks/db_mock.cr

This is required by changes made in crystal-db v0.11.0

add #next_column_index to db mocker

---

docs/crud.md
docs/imports.md
docs/migrations.md
docs/models.md
docs/querying.md
docs/readme.md
docs/relationships.md
docs/validations.md
src/adapter/base.cr
src/adapter/mysql.cr
src/granite.cr
src/granite/association_collection.cr
src/granite/associations.cr
src/granite/columns.cr
src/granite/query/assemblers/base.cr
src/granite/query/builder.cr
src/granite/querying.cr
src/granite/transactions.cr

My fork has been getting a bit ahead so i wanted to open a PR with my working branch.
This includes the following bug fixes:
* fix allowing enum columns
* #455
* #454
* Fix issue where primary key can be pushed twice on create
* fix infinite recursion when searching with enum
It also includes the following enhancements:
* ameba recomendations
* add retry to adapter base
* add support for querying with Array(UUID)
* add `Relationship` annotation that is applied to methods which are defined relationships

Merge fork with enhancements/fixes

---

src/granite/querying.cr

Checking for existing records where column type is `bool` if you search with criteria where the column is `false` it will query it as `is NULL` instead of `is false`.
```
criteria: {scryfall_uuid: UUID(9c198ffd-50c8-46ae-a4bd-75c9d39f40de),
inventory_uuid: UUID(9ae21165-09d8-4a33-88ec-5dbf0b4b8f4a),
foil: false,
etched: false}
2021-08-31T20:04:53.403044Z  DEBUG - db: Executing query -- query: "SELECT EXISTS(SELECT 1 FROM `card_record` WHERE `card_record`.`scryfall_uuid` = ? AND `card_record`.`inventory_uuid` = ? AND `card_record`.`foil` IS NULL AND `card_record`.`etched` IS NULL)", args: ["9c198ffd-50c8-46ae-a4bd-75c9d39f40de", "9ae21165-09d8-4a33-88ec-5dbf0b4b8f4a"]
does not exist
```
after fix:
```
criteria: {scryfall_uuid: UUID(9c198ffd-50c8-46ae-a4bd-75c9d39f40de),
inventory_uuid: …
```

fix build_find_by_clause for bool values

---

spec/granite/exceptions/record_invalid_spec.cr
spec/granite/exceptions/record_not_destroyed_spec.cr
src/granite/exceptions.cr

Hello,
I struggled to display error messages from Granite when testing my code. The `RecordNotSaved` and `RecordNotDestroyed` messages are too generic and do not provide any clue about what is going on when an error is triggered when calling `save!` or `destroy!`.
We could, indeed, call `save` instead of `save!` and collect those error messages. But it would be cumbersome and need to add boilerplate everywhere. IMHO, it is usually simpler (and preferred) to manage exceptions.
So, I've added the message of the first error in the model to ease the feedback loop and have some understandings on the error directly instead of having to add code around to know what is the real issue.
Please let me know if you disagree with this and if you would see a better implementation.
Cheers!

Add context to RecordNotSaved/RecordNotDestroyed error messages

---

src/granite/transactions.cr

If a column is named `created_at` or `updated_at` is not a type `Time?`, then the following occurs:
```There was a problem expanding macro 'macro_4801706624'
Code in lib/granite/src/granite/transactions.cr:82:5
82 | {% if @type.instance_vars.select { |ivar| ivar.annotation(Granite::Column) }.map(&.name.stringify).includes? "created_at" %}
^
Called macro defined in lib/granite/src/granite/transactions.cr:82:5
82 | {% if @type.instance_vars.select { |ivar| ivar.annotation(Granite::Column) }.map(&.name.stringify).includes? "created_at" %}
Which expanded to:
> 1 |
> 2 |       if mode == :create
> 3 |         @created_at = time.at_beginning_of_second
^---------------------
```
this simply adds a type check.

Add a check to ensure created_at and updated_at are Time

---

.env
.gitignore
export.sh
spec/adapter/adapters_spec.cr
spec/granite/connection_management_spec.cr
spec/granite/connection_switching_spec.cr
spec/spec_helper.cr
spec/spec_models.cr
src/granite/base.cr
src/granite/connection_management.cr
src/granite/connections.cr
src/granite/query/builder.cr
src/granite/querying.cr
src/granite/table.cr

This is the first step in handling #475. The next step is to create a mechanism that lets the adapter know about the reader/writer if they exist and decide which one to run based on the information provided to it.
I however, deem this a good milestone for a PR. This change is large and handling merge conflicts would be a pain. Better to PR it in step by step.

Feature: Read replica support

---

docker/docker-compose.sqlite.yml
docs/crud.md
spec/granite/transactions/create_spec.cr
spec/granite/transactions/save_spec.cr
spec/granite/transactions/update_spec.cr
src/granite/transactions.cr

Resolves #318
This adds the ability to pass `skip_timestamps: true` to `update` and `update!` methods. To do this I had to change the `save` method to accept `skip_timestamps` so to avoid inconsistent behaviour I have also added the option to the `create` and `create!` methods.
To achieve this I had to remove the type definition of `args` on the method definition so that either a `Granite::ModelArgs` or a `NamedTuple` can be passed in with `skip_timestamps`, I originally added another method overload for this case as you can see in the first commit e6f917e4e383d69672a6acb6c5f39c299ef58d13. Open to thoughts on this.
I have also updated the crud.md docs to describe this feature and added a missing example for `save(validate: false)`

Add `skip_timestamps` option

---

.github/workflows/spec.yml

Currently ameba is not in the pipeline however is used when running the tests within Docker (command in the readme). It would be useful for these to be consistent.
I cannot test the pipeline changes locally so it may need tweaking once the workflow has been approved.

ci: add ameba linting to formatting ci job

---

spec/granite/querying/passthrough_spec.cr

This fixes an issue when running against postgres `Expected PQ::Frame::ParseComplete but got PQ::Frame::ReadyForQuery`
The offending spec was: `spec/granite/querying/passthrough_spec.cr` Anything that ran after this spec would throw the above error.
Simply closing the result set before moving on fixed the errors.
Co-authored-by: @jphaward <jphaward@gmail.com>

Close result set at the end of test in passthrough_spec.cr

---

spec/granite/migrator/migrator_spec.cr
spec/granite/transactions/create_spec.cr
src/adapter/mysql.cr

#486 which was recently merged was failing on the mysql tests for skipping timestamps on create. This is due to mysql not allowing NULL values on timestamps by default - [docs here](https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html)

Fix mysql to allow timestamps null

---

shard.yml
src/adapter/base.cr
src/granite/connections.cr
src/granite/query/assemblers/base.cr
src/granite/query/builder.cr
src/granite/querying.cr

This PR upgrades ameba to v1.50 which fixes the compatibility issues with later versions of Crystal on the post install step.
It also fixes the new linting requirements of v1.5.0.
There are a few linting errors which are not resolved in this PR but are instead covered in #487 and #492.
Once all are merged the ci pipeline *should* be back to green

493 upgrade ameba shard to latest version

---

spec/granite/connection_management_spec.cr
src/granite/connections.cr

Currently ameba linting fails due to the usage of not_nil!. This can be fixed by giving the not_nil! an argument of an error message however I've chosen to prioritise readability.

refactor: fix linting issues on not_nil! usage

---

spec/granite_spec.cr

Fixes #488 where there were previous inconsistencies of yaml across different OS / libraries which are now consistent.

test: fix to_yaml nil value representation for mac

---

src/granite/connection_management.cr
src/granite/connections.cr

- Changed connection period to use less memory by switching to Int32 from Int64 
- Changed reader/writer to allow `nil` now that we have `nil` checks for when the connections are being used. This resolves the issue with Amber not being able to boot.

Fixed bug preventing Amber from booting

---

docs/crud.md
spec/granite/querying/reload_spec.cr
src/granite/base.cr
src/granite/querying.cr

Add reload method

---

src/granite/querying.cr

I made a mistake in #491 when I applied your suggestion, I forgot to move the macro condition wrapping the entire method 🤦🏼‍♂️
This fixes that.

Fix reload macro to include method in docs

---

src/adapter/base.cr

Has been broken since it was originally implemented in 3d73a5de.
Noticed while implementing a similar method in our own code. @Blacksmoke16 is something of this ilk (more readable short span printing) a candidate for stdlib do you think?

Fix logging of query durations, which were off by 10x for µs precision

---

src/granite/connection_management.cr
src/granite/transactions.cr

I'm working on a project that's generating a couple million rows to enter into a sqlite database. For reasons I haven't figured out yet, I'm getting a "cannot allocate memory" error when a new `spawn` call is being made (I've verified the machine this program is running on has plenty of memory and isn't getting anywhere near the limit, and other fiber allocations seem to be working just fine :shrug: ). Regardless of the what's causing _that_, I was able to update some error propagation in granite to discover an unnecessary `spawn` call being made in the event the `@@reader_adapter` and `@@writer_adapter` are the same adapter. Making this PR to include the error propagation changes as well as fixing the unnecessary `spawn` call.

Propagate original callstack, save a fiber allocation if unnecessary
